maintainer       "Marshall University"
maintainer_email "itisystems@marshall.edu"
license          "Apache 2.0"
description      "Installs/Configures gitlab"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.16"
depends          "git"
depends          "gitolite"
depends          "sqlite"
#depends          "redis"
#depends          "redis2"
depends          "redisio::install"
depends          "redisio::enable"
